### ISSUE TITLE
Export problem on index.js

### ISSUE THREAD

**Issue by abimaelneto** [stefandesu/eva-icons-vue#1]
Hey, there! 

I've just installed the library and followed the README. 

I received the following message:

> Module parse failed: Unexpected token (18:9)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> | 
> | export * from "./icons"
> > export * as icons from "./icons"
> | export { EvaIcon }

Don't know if the library requires any Webpack configuration, but, anyway, commenting the marked line makes it to work fine.

Sorry if I'm misunderstanding anything here. Just trying to help :)

Congrats for your work and thank you!

**Comment by stefandesu** [comment]
Hey!

Seems like the `export * from "./icons"` syntax is not supported everywhere. I usually build my Vue projects with [Vite](https://vitejs.dev) and there it works fine out of the box. What are you using for your project, Vue CLI?

Commenting out that line should mean that you can't import individual icons anymore, but adding all icons should still work.

**Comment by abimaelneto** [comment]
Yeah, I'm using the Vue CLI! 

Well, as I need many icons, I would rather import all of them together, so It's not a problem for me.
But it looks like building with Vite is a dependency too.

**Comment by stefandesu** [comment]
Just updated the package, it should work now. 👍 Thanks for your input!
